### ISSUE TITLE
Linux - unable to connect to any server

### ISSUE THREAD

**Issue by titibandit** [puyonexus/puyovs#41]
Hi,
I'm unable to connect to the online servers (I've tried ds-net.jp and bayoen.fr).
When entering a username and a password and then clicking on "connect", the connect button greys itself out for a moment, making it look like it's trying to connect, and after a certain time, the button becomes actionable again (nothing happened in between).
There is no relevant information delivered on the console's standard output.
I've tried using a client compiled from the current master branch, as well as with a client compiled from the v31 tag. Both act the same way.

I don't know if this is a Linux specific issue, as I'm unable to try using other platforms.
Any pointers?
Cheers.

**Comment by jchv** [comment]
Have you ever been able to connect to the servers or is this your first time attempting to? I'm not really sure what's wrong off the top of my head.

**Comment by titibandit** [comment]
Okay, I can close this issue, as I figured out that it was my university's network that was getting in the way of connecting to the servers. I have another problem now, but I'll open issue for that

**Comment by jchv** [comment]
Sounds like we need to do a better job with error handling and reporting, though... but good to know.
