### ISSUE TITLE
"All Clear" animation bug in fever mode

### ISSUE THREAD

**Issue by Minkachrgza-e** [puyonexus/puyovs#55]
you can fully see "All Clear" first time of game window, but from second time you only see a disappearing of its texts not in a fully appearance.

only happens in fever and same thing would happen in every time when you launch fever game window.

**Comment by LossRain** [comment]
Addressed by #57, please verify that the bug has been fully fixed on your end.

**Comment by Minkachrgza-e** [comment]
I forgot to close issues, fixed in #57.
